from __future__ import annotations

from datetime import date
from typing import Protocol

import pandas as pd


class MarketDataProvider(Protocol):
    def trading_days(self, start: date, end: date) -> list[pd.Timestamp]: ...
    def latest_trading_day(self) -> str: ...
    def stock_universe(self, as_of: str) -> pd.DataFrame: ...
    def etf_universe(self, as_of: str) -> pd.DataFrame: ...
    def stock_snapshot(self, day: str) -> pd.DataFrame: ...
    def etf_snapshot(self, day: str) -> pd.DataFrame: ...
    def cap_snapshot(self, day: str) -> pd.DataFrame: ...
    def fundamental_snapshot(self, day: str) -> pd.DataFrame: ...
    def history(self, ticker: str, start: str, end: str, kind: str = "stock", adjusted: bool = True) -> pd.DataFrame: ...
